import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LanguageContext = createContext(null);

const translations = {
  en: {
    navbar: {
      home: "Home",
      aiChat: "AI Chat",
      solutions: "Solutions",
      resources: "Resources",
      news: "News",
      about: "About",
      contact: "Contact",
      startFree: "Start Free",
      login: "Login",
      logout: "Logout",
      search: "Search",
      selectLanguage: "Language",
    },
    auth: {
      welcomeBack: "Welcome back",
      createAccount: "Create account",
      signInDesc: "Sign in to save your conversations.",
      joinDesc: "Join Her Legal anonymously.",
      username: "Username",
      email: "Email",
      phone: "Phone",
      password: "Password",
      pleaseWait: "Please wait...",
      signIn: "Sign In",
      createAccountBtn: "Create Account",
      dontHaveAccount: "Don't have an account?",
      alreadyHaveAccount: "Already have an account?",
      signUp: "Sign up",
      signInAction: "Sign in",
    },
    footer: {
      platform: "Platform",
      company: "Company",
      support: "Support",
      aiAssistant: "AI Assistant",
      legalTopics: "Legal Topics",
      documents: "Documents",
      knowledgeHub: "Knowledge Hub",
      about: "About",
      contact: "Contact",
      privacy: "Privacy",
      terms: "Terms",
      helpline: "Helpline",
      faq: "FAQ",
      safety: "Safety",
      description: "Making legal information accessible, understandable, and actionable for every woman in Nepal.",
      description: "Making legal information accessible, understandable, and actionable for every woman in Nepal.",
      rightsReserved: "All rights reserved.",
      builtWith: "Built with ❤️ for every woman in Nepal",
    },
    chatbotWidget: {
      title: "Saathi — Here to help",
      greet: "Hi, I'm here to help with questions about your rights. Ask me anything.",
      placeholder: "Type your question...",
      send: "Send",
      thinking: "Thinking...",
      error: "Something went wrong. Please try again.",
      noResponse: "No response",
      toggleNepali: "नेपाली",
      toggleEnglish: "English",
    },
    chatPage: {
      title: "Saathi AI",
      newConversation: "New Conversation",
      recent: "Recent",
      loading: "Loading...",
      noConversations: "No conversations yet",
      conversation: "Conversation",
      savedDocuments: "Saved Documents",
      bookmarks: "Bookmarks",
      settings: "Settings",
      emergencyHelp: "Emergency Help",
      welcomeBadge: "AI Legal Assistant",
      welcomeTitle: "Know your rights.",
      welcomeAccent: "Before life asks.",
      welcomeSub: "Ask anything about women's legal rights in Nepal. Free, anonymous, private.",
      promptHint: "Ask about your legal rights...",
      noMessages: "Ask something to start your conversation.",
      you: "You",
      assistant: "Saathi",
      needHelp: "Need Immediate Help?",
      legalGuidance: "This is general legal guidance and not legal advice. Consult a qualified lawyer for your specific situation.",
      categories: [
        { title: "Property Rights", prompt: "What are my property rights in Nepal?" },
        { title: "Employment", prompt: "What are my workplace rights in Nepal?" },
        { title: "Marriage & Divorce", prompt: "How do I file for divorce in Nepal?" },
        { title: "Domestic Violence", prompt: "How to report domestic violence in Nepal?" },
        { title: "Women's Rights", prompt: "What are women's constitutional rights in Nepal?" },
        { title: "Citizenship", prompt: "Explain citizenship laws in Nepal" },
        { title: "Cyber Crime", prompt: "How to report cyber crime in Nepal?" },
        { title: "Police & FIR", prompt: "How do I file a police complaint in Nepal?" },
      ],
      promptIdeas: [
        "Can my employer fire me without notice?",
        "Explain divorce procedures in Nepal",
        "What is the legal age for marriage?",
        "Create a rental agreement template",
      ],
      followUpOptions: [
        "Explain Simply",
        "Generate Letter",
        "Show Related Laws",
        "Find Legal Aid",
      ],
      helpButtons: {
        savedDocuments: "Saved Documents",
        bookmarks: "Bookmarks",
        settings: "Settings",
      },
      actionPanel: {
        keyTakeaways: "Key Takeaways",
        relatedLaws: "Related Laws",
        recommendedDocuments: "Recommended Documents",
        legalAidContacts: "Legal Aid Contacts",
        nextStep: "Next Step",
      },
      panelLinks: {
        complaintLetter: "Complaint Letter",
        rentalAgreement: "Rental Agreement",
        findLawyer: "Find Nearby Lawyer",
      },
    },
    home: {
      hero: {
        badge: "AI-Powered Legal Guidance",
        title: "Know your rights.",
        accent: "Before life asks.",
        subtitle: "Understand Nepali law in plain language. Get instant answers, generate documents, and take action — all in one place.",
        startAI: "Start AI Assistant",
        explore: "Explore Legal Topics",
        joinCommunity: "Join Community",
        anonymousShield: "100% Anonymous",
        privateSecure: "Private & Secure",
        nepalSpecific: "Nepal-Specific",
      },
      trustItems: [
        "AI-Powered Guidance",
        "Women Focused",
        "Privacy First",
        "Nepal Specific",
        "Legal Information",
        "Document Assistance",
      ],
      problem: {
        title: "Legal information shouldn't require a lawyer to understand.",
        desc: "In Nepal, most women face three barriers when trying to understand their legal rights.",
        cards: [
          { title: "Confusing Laws", desc: "Legal documents are written in complex language that's nearly impossible to navigate without professional help." },
          { title: "Expensive Consultations", desc: "Private lawyers charge NPR 1,000–5,000 per consultation — out of reach for most Nepali women." },
          { title: "No Trusted Guidance", desc: "Fear of judgment, stigma, and lack of anonymous resources keep women from seeking the help they need." },
        ],
      },
      topicsSection: {
        label: "Legal Topics",
        title: "Know your rights, across every area of life",
      },
      faq: [
        { q: "Is my identity protected?", a: "Absolutely. All interactions with Her Legal are anonymous. We don't collect personal information. Your privacy and safety are our top priorities." },
        { q: "How do I get legal help?", a: "Start by asking our AI assistant below — it's free and instant. For specific legal guidance, we can connect you with our network of legal partners through the Contact page." },
        { q: "Is this service free?", a: "Yes. Every feature — AI legal assistant, document templates, knowledge hub, and community support — is completely free." },
        { q: "What if I need emergency help?", a: "If you're in immediate danger, call the Women's Helpline at 1145 or Police at 100. Our Emergency section has all the numbers." },
      ],
      reality: {
        label: "The Reality",
        title: "Most women in Nepal face legal challenges alone.",
        desc: "The law is written in language that requires years to understand. Lawyers charge fees most cannot afford. And asking for help often means risking judgment.",
        stat1: "of Nepali women are unaware of their legal rights",
        stat2: "never seek legal help due to cost or fear of judgment",
      },
      ai: {
        headerTitle: "Saathi — AI Legal Assistant",
        online: "Online",
        welcomeMsg: "Ask me anything about Nepali law.",
        mockupQuestion: "What are my rights during divorce?",
        mockupSource: "Muluki Civil Code, 2074",
        mockupItem1: "Equal division of jointly acquired property",
        mockupItem2: "Alimony if you are financially dependent",
        mockupItem3: "Child custody based on the child's best interest",
        mockupPlaceholder: "Ask a follow-up...",
        label: "AI Legal Assistant",
        title: "You ask. It answers. In plain language.",
        desc: "Trained on Nepal's constitution, civil code, labour act, and 30+ legal documents. Your personal legal guide, available anytime, completely free.",
        feature1: "Instant answers, 24/7",
        feature2: "Nepali & English support",
        feature3: "Sources cited for every claim",
        feature4: "100% anonymous",
        cta: "Try the AI Assistant",
        saveAnswer: "Save Answer",
        generateDoc: "Generate Document",
        share: "Share",
      },
      documents: {
        label: "Document Generator",
        title: "One click. A legal document. Ready to file.",
        desc: "From complaint letters to affidavits. Answer simple questions, and the AI drafts a complete, properly formatted legal document.",
        type1: "Complaint Letter",
        type2: "Legal Notice",
        type3: "Affidavit",
        type4: "Agreement",
        type5: "Application",
        type6: "Demand Letter",
        cta: "Generate a Document",
        previewTitle: "Complaint Letter Draft",
        previewFootnote: "Generated by AI — ready to review and download",
      },
      knowledge: {
        label: "Knowledge Hub",
        title: "Learn your rights. On your own time.",
        searchPlaceholder: "Search articles...",
      },
      communitySection: {
        label: "Community",
        stat: "women in our community",
        title: "You're not alone. Thousands have shared.",
        desc: "A safe space to share anonymously, ask questions, and support other women facing legal challenges. No judgment. Just understanding.",
        cta: "Join the Community",
      },
      stats: {
        activeUsers: "Active Users",
        aiAnswers: "AI Answers",
        documentsGenerated: "Documents Generated",
        communityStories: "Community Stories",
      },
      emergency: {
        label: "Need Immediate Help?",
        title: "You are not alone. Help is one call away.",
        desc: "Free, confidential support available 24/7. Trained professionals are ready to listen.",
        womensHelpline: "Women's Helpline",
        policeEmergency: "Police Emergency",
        legalAid: "Legal Aid Commission",
      },
      trust: {
        label: "Why Her Legal",
        title: "Built on trust. Guaranteed by design.",
        feature1Title: "Complete Anonymity",
        feature1Desc: "No personal information required. Your identity is never stored or shared.",
        feature2Title: "End-to-End Privacy",
        feature2Desc: "All conversations encrypted. We don't track, log, or sell your data.",
        feature3Title: "Built for Nepal",
        feature3Desc: "Every answer references actual Nepali legislation. From the Constitution to the Civil Code.",
        feature4Title: "Free for Everyone",
        feature4Desc: "All features are completely free. No hidden charges, no premium tiers.",
        faqTitle: "Common questions",
        faq1Q: "Is my identity really protected?",
        faq1A: "Absolutely. All interactions are completely anonymous. We don't store personal information, and your identity is never revealed to other users.",
        faq2Q: "How accurate is the AI?",
        faq2A: "Our AI is trained on 30+ Nepali legal texts including the Constitution, Muluki Civil Code, Labour Act, and Domestic Violence Act. Always verify critical decisions with a qualified lawyer.",
        faq3Q: "Can I use the site in Nepali?",
        faq3A: "Yes. The platform supports both English and Nepali. Ask questions in either language and receive answers in the same language.",
      },
      cta: {
        title: "Legal guidance.",
        accent: "Made understandable.",
        desc: "Start with Her Legal. It's free, anonymous, and built for every woman in Nepal.",
        cta: "Get Started",
      },
    },
    aboutUs: {
      label: "About Us",
      title: "Empowering women through legal awareness",
      desc: "Her Legal is a Nepal-based initiative dedicated to providing women with accessible legal information, a safe community to share their stories, and compassionate support when they need it most.",
      cards: [
        { title: "Our Mission", desc: "To bridge the gap between Nepali women and their legal rights through education, community support, and accessible resources." },
        { title: "Our Vision", desc: "A Nepal where every woman is informed of her rights, empowered to speak up, and supported in her journey toward justice." },
        { title: "Our Values", desc: "Safety, confidentiality, empathy, and unwavering belief in every woman's right to dignity and legal protection." },
      ],
    },
    campaigns: {
      label: "Take Action",
      title: "Campaigns & Programs",
      items: [
        { title: "Know Your Rights", tag: "Workshop", desc: "Free legal literacy workshops across all seven provinces of Nepal, covering domestic violence, property rights, and workplace protections." },
        { title: "Safe Voices", tag: "Campaign", desc: "An anonymous storytelling campaign that empowers women to share their experiences and find solidarity in community." },
        { title: "Sathi Helpline", tag: "Service", desc: "A confidential helpline connecting women with legal advisors, counselors, and emergency support services." },
      ],
    },
    contactHelp: {
      label: "Get in Touch",
      title: "Contact & Help",
      desc: "Reach out to us. Whether you need legal guidance, want to share your story, or just need someone to listen — we're here.",
      emergencyTitle: "Emergency Helplines",
      emailTitle: "Email Us",
      generalInquiry: "For general inquiries:",
      email: "hello@herlegal.org",
      followTitle: "Follow Us",
      socials: ["Facebook", "Instagram", "Twitter"],
    },
    confessions: {
      label: "Share Your Story",
      title: "Your voice, your truth",
      desc: "Share your experience anonymously. You are not alone.",
      placeholder: "What would you like to share?",
      anonymous: "Post anonymously",
      posting: "Posting...",
      share: "Share →",
      anonymousAuthor: "Anonymous",
      replyPlaceholder: "Write a reply...",
      reply: "Reply",
    },
    news: {
      label: "Updates",
      title: "News & Magazines",
      articles: [
        { title: "New Legal Aid Centers Opening in Province 2", date: "Jun 28, 2026", excerpt: "Five new legal aid centers are opening across Province 2 to provide free legal counsel to women in rural areas." },
        { title: "Domestic Violence Law Amendments: What You Need to Know", date: "Jun 15, 2026", excerpt: "Recent amendments to domestic violence laws strengthen protections for survivors. Here's a plain-language breakdown." },
        { title: "Her Legal Reaches 500 Women Helped Milestone", date: "May 30, 2026", excerpt: "We're humbled to share that Her Legal has now supported over 500 women across Nepal with legal guidance and support." },
      ],
    },
    team: {
      label: "People",
      title: "Our Team",
      members: [
        { name: "Aarati Gurung", role: "", initials: "AG" },
        { name: "Dalsara Soti Magar", role: "", initials: "DSM" },
        { name: "Nandani Sewa", role: "", initials: "NS" },
        { name: "Sofiya Kunwar", role: "", initials: "SK" },
      ],
    },
    notFound: {
      title: "Page not found",
      desc: "The page you're looking for doesn't exist or has been moved.",
      goHome: "Go Home",
    },
    common: {
      justNow: "just now",
      mAgo: "m ago",
      hAgo: "h ago",
      dAgo: "d ago",
      anonymous: "Anonymous",
      loading: "Loading...",
      saving: "Saving...",
      save: "Save",
      saved: "Saved",
      delete: "Delete",
      report: "Report",
      share: "Share",
      cancel: "Cancel",
      confirm: "Confirm",
      back: "Back",
      continue: "Continue",
      search: "Search",
      noResults: "No results found",
      error: "Something went wrong. Please try again.",
      success: "Success",
      dashboard: "Dashboard",
      settings: "Settings",
      notifications: "Notifications",
      profile: "Profile",
      security: "Security",
      signOut: "Sign out",
      backToSite: "Back to site",
    },
    community: {
      title: "Community",
      subtitle: "Share, learn, and support each other — anonymously if you choose.",
      shareStory: "Share your story",
      createPost: "Create post",
      latest: "Latest",
      trending: "Trending",
      loadingPosts: "Loading posts...",
      noPosts: "No posts yet",
      noPostsDesc: "Be the first to share your story in this category.",
      all: "All",
      womenRights: "Women's Rights",
      employment: "Employment",
      marriage: "Marriage",
      property: "Property",
      domesticViolence: "Domestic Violence",
      cyberCrime: "Cyber Crime",
      citizenship: "Citizenship",
      familyLaw: "Family Law",
      general: "General",
      anonymousNames: ["Anonymous Lotus", "Anonymous Hope", "Anonymous Citizen", "Anonymous Sparrow", "Anonymous Orchid", "Anonymous River"],
    },
    createPost: {
      back: "Back to community",
      anonymousHint: "Your identity is hidden. No one will see your name.",
      publicHint: "This post will show your username.",
      anonymous: "Anonymous",
      public: "Public",
      title: "Share your story",
      subtitle: "Your voice matters. Share anonymously or publicly.",
      titleLabel: "Title",
      titlePlaceholder: "What's on your mind?",
      categoryLabel: "Category",
      storyLabel: "Your story",
      storyPlaceholder: "Share your experience, ask for advice, or start a discussion...",
      charCount: "/10000",
      tagsLabel: "Tags (optional, comma separated)",
      tagsPlaceholder: "e.g. workplace, harassment, advice",
      posting: "Posting...",
      submit: "Share with community",
      validationError: "Title and text are required",
      apiError: "Failed to create post",
    },
    postDetail: {
      community: "Community",
      helpful: "Helpful",
      supportive: "Supportive",
      insightful: "Insightful",
      comments: "Comments",
      commentPlaceholder: "Share your thoughts...",
      postAnonymous: "Post anonymously",
      send: "Send",
      signInToComment: "Sign in to comment",
      noComments: "No comments yet. Be the first to share your thoughts.",
      reportPlaceholder: "Why are you reporting this? (required)",
      submitReport: "Submit report",
      deleteConfirm: "Delete this post?",
      saves: "saves",
    },
    dashboard: {
      title: "Dashboard",
      overview: "Overview",
      activity: "Activity",
      aiConversations: "AI Conversations",
      savedDocuments: "Saved Documents",
      bookmarks: "Bookmarks",
      communityPosts: "Community Posts",
      quickActions: "Quick actions",
      askAI: "Ask AI Assistant",
      generateDoc: "Generate Document",
      community: "Community",
      legalDocuments: "Legal Documents",
      legalGlossary: "Legal Glossary",
      recentActivity: "Recent activity",
      noActivity: "No recent activity",
      activityTabDesc: "Your recent activity across the platform.",
      noActivityDesc: "No activity yet. Start by chatting with the AI assistant or exploring the community.",
      startChatting: "Start chatting",
      settingsTabDesc: "Manage your account settings.",
      accountCreated: "Account created",
      welcome: "Welcome,",
      welcomeSub: "Here's what's happening with your account.",
      profileCard: "Profile",
      profileCardDesc: "Update your name, email, and photo",
      securityCard: "Security",
      securityCardDesc: "Password and authentication",
      notificationsCard: "Notifications",
      notificationsCardDesc: "Manage notification preferences",
    },
    settingsProfile: {
      title: "Profile",
      subtitle: "Update your personal information.",
      email: "Email",
      username: "Username",
      phone: "Phone",
      saveChanges: "Save changes",
      profileUpdated: "Profile updated",
      updateFailed: "Update failed",
    },
    settingsSecurity: {
      title: "Security",
      subtitle: "Change your password.",
      currentPassword: "Current password",
      newPassword: "New password",
      passwordPlaceholder: "At least 6 characters",
      confirmPassword: "Confirm new password",
      changePassword: "Change password",
      passwordsMismatch: "Passwords do not match",
      passwordChanged: "Password changed successfully",
      changeFailed: "Failed to change password",
    },
    settingsNotifications: {
      title: "Notifications",
      subtitle: "Manage your notification preferences.",
      replies: "Replies",
      repliesDesc: "Get notified when someone replies to your posts",
      communityActivity: "Community activity",
      communityActivityDesc: "Stay updated on community activity",
      legalUpdates: "Legal updates",
      legalUpdatesDesc: "Receive updates about Nepali law changes",
      savePreferences: "Save preferences",
      preferencesSaved: "Preferences saved",
    },
    documents: {
      title: "Legal Documents",
      subtitle: "Generate, save, and download legal documents.",
      templates: "Templates",
      documentTemplates: "Document Templates",
      savedDocuments: "Saved Documents",
      noSaved: "No saved documents yet. Generate one above.",
      generate: "Generate Document",
      generating: "Generating...",
      editForm: "Edit form",
      download: "Download",
      generationFailed: "Generation failed",
      saveFailed: "Save failed",
      deleteConfirm: "Delete this document?",
      complaintLetter: "Complaint Letter",
      legalNotice: "Legal Notice",
      affidavit: "Affidavit",
      agreement: "Agreement",
      application: "Application",
      demandLetter: "Demand Letter",
    },
    glossary: {
      title: "Legal Glossary",
      subtitle: "Common Nepali legal terms explained in plain language.",
      searchPlaceholder: "Search terms or definitions...",
      terms: "terms",
      courtProcedure: "Court Procedure",
      familyLaw: "Family Law",
      criminalLaw: "Criminal Law",
      propertyLaw: "Property Law",
      civilLaw: "Civil Law",
      constitutionalLaw: "Constitutional Law",
      intellectualProperty: "Intellectual Property",
      employmentLaw: "Employment Law",
      disputeResolution: "Dispute Resolution",
      immigration: "Immigration",
    },
    notificationsPage: {
      title: "Notifications",
      markAllRead: "Mark all read",
      clearAll: "Clear all",
      empty: "No notifications yet",
      confirmClear: "Are you sure you want to delete all notifications? This action cannot be undone.",
    },
    onboarding: {
      step0Title: "Choose your language",
      step0Desc: "Select your preferred language for the platform.",
      english: "English",
      nepali: "नेपाली",
      step1Title: "What interests you?",
      step1Desc: "Pick topics you'd like to learn about. You can change these later.",
      step2Title: "Community preferences",
      step2Desc: "Customize your community experience.",
      anonymousPosting: "Anonymous posting",
      anonymousPostingDesc: "Your identity is hidden from the public",
      receiveReplies: "Receive replies",
      receiveRepliesDesc: "Get notified when someone replies to your posts",
      receiveNotifications: "Receive notifications",
      receiveNotificationsDesc: "Stay updated on community activity",
      legalUpdates: "Legal updates",
      legalUpdatesDesc: "Receive updates about Nepali law changes",
      step3Title: "Your privacy matters",
      step3Desc: "Here's how we protect you on Her Legal.",
      privacyBullet1: "Your identity is hidden from the public",
      privacyBullet2: "Only authorized moderators can investigate abuse",
      privacyBullet3: "Your documents and conversations are private",
      privacyBullet4: "You control whether each post is anonymous or public",
      ready: "You're all set! Let's get started.",
      goToDashboard: "Go to dashboard",
    },
  },
  ne: {
    navbar: {
      home: "गृह",
      aiChat: "एआई कुराकानी",
      solutions: "समाधान",
      resources: "स्रोतहरू",
      news: "समाचार",
      about: "हाम्रोबारे",
      contact: "सम्पर्क",
      startFree: "निशुल्क सुरु गर्नुहोस्",
      login: "लगइन",
      logout: "लगआउट",
      search: "खोज्नुहोस्",
      selectLanguage: "भाषा",
    },
    auth: {
      welcomeBack: "पुन: स्वागत",
      createAccount: "खाता सिर्जना गर्नुहोस्",
      signInDesc: "तपाईंका संवादहरू बचत गर्न साइन इन गर्नुहोस्।",
      joinDesc: "Her Legal मा अनाम रुपमा सामेल हुनुहोस्।",
      username: "प्रयोगकर्ता नाम",
      email: "इमेल",
      phone: "फोन",
      password: "पासवर्ड",
      pleaseWait: "कृपया पर्खनुहोस्...",
      signIn: "साइन इन",
      createAccountBtn: "खाता सिर्जना गर्नुहोस्",
      dontHaveAccount: "खाता छैन?",
      alreadyHaveAccount: "पहिले नै खाता छ?",
      signUp: "साइन अप",
      signInAction: "साइन इन",
    },
    footer: {
      platform: "प्लेटफर्म",
      company: "कम्पनी",
      support: "समर्थन",
      aiAssistant: "एआई सहायक",
      legalTopics: "कानुनी विषयहरू",
      documents: "कागजातहरू",
      knowledgeHub: "ज्ञान हब",
      about: "हाम्रोबारे",
      contact: "सम्पर्क",
      privacy: "गोपनीयता",
      terms: "सर्तहरू",
      helpline: "हेल्पलाइन",
      faq: "FAQ",
      safety: "सुरक्षा",
      rightsReserved: "सबै अधिकार सुरक्षित छन्।",
      builtWith: "नेपालका हरेक महिलाका लागि बनाइयो",
    },
    chatbotWidget: {
      title: "Saathi — सहयोगका लागि तयार",
      greet: "नमस्ते, म तपाईंको अधिकारसम्बन्धी प्रश्नमा सहयोग गर्न यहाँ छु।",
      placeholder: "आफ्नो प्रश्न लेख्नुहोस्...",
      send: "पठाउनुहोस्",
      thinking: "सोच्दैछ...",
      error: "केही गलत भयो। कृपया फेरि प्रयास गर्नुहोस्।",
      noResponse: "उत्तर छैन",
      toggleNepali: "नेपाली",
      toggleEnglish: "English",
    },
    chatPage: {
      title: "Saathi AI",
      newConversation: "नयाँ संवाद",
      recent: "हालैका",
      loading: "लोड हुँदैछ...",
      noConversations: "अहिले कुनै संवाद छैन",
      conversation: "संवाद",
      savedDocuments: "पुस्तिकाहरू",
      bookmarks: "बुकमार्क",
      settings: "सेटिङ्स",
      emergencyHelp: "आपतकालीन सहयोग",
      welcomeBadge: "एआई कानुनी सहायक",
      welcomeTitle: "आफ्नो अधिकारहरु जान्नुहोस्।",
      welcomeAccent: "जीवनले सोध्नुअघि।",
      welcomeSub: "नेपालमा महिलासम्बन्धी कानुनी अधिकारहरू बारे केही सोध्नुहोस्। निःशुल्क, अनाम, निजी।",
      promptHint: "आफ्नो कानुनी अधिकारहरू बारे सोध्नुहोस्...",
      noMessages: "तपाईंको संवाद सुरु गर्न केही सोध्नुहोस्।",
      you: "तपाईं",
      assistant: "Saathi",
      needHelp: "तत्काल सहयोग चाहियो?",
      legalGuidance: "यो सामान्य कानुनी मार्गदर्शन हो र कानुनी सल्लाह होइन। तपाईंको विशेष परिस्थितिका लागि योग्य वकिलसँग परामर्श गर्नुहोस्।",
      categories: [
        { title: "संपत्ति अधिकार", prompt: "नेपालमा मेरा सम्पत्ति अधिकारहरू के हुन्?" },
        { title: "रोजगारी", prompt: "मेरा कार्यस्थल अधिकारहरू के हुन्?" },
        { title: "विवाह र डिभोर्स", prompt: "नेपालमा विभाजन कसरी दायर गर्ने?" },
        { title: "घरेलु हिंसा", prompt: "नेपालमा घरेलु हिंसा कसरी रिपोर्ट गर्ने?" },
        { title: "महिलाका अधिकार", prompt: "नेपालमा महिलाका संवैधानिक अधिकारहरू के हुन्?" },
        { title: "नागरिकता", prompt: "नेपालको नागरिकता कानून व्याख्या गर्नुहोस्" },
        { title: "साइबर अपराध", prompt: "नेपालमा साइबर अपराध कसरी रिपोर्ट गर्ने?" },
        { title: "प्रहरी र एफआईआर", prompt: "नेपालमा प्रहरी उजुरी कसरी दायर गर्ने?" },
      ],
      promptIdeas: [
        "के मेरो नियोक्ताले सूचना बिना मलाई हटाउन सक्छ?",
        "नेपालमा विभाजन प्रक्रिया स्पष्टीकरण गर्नुहोस्",
        "विवाहको कानुनी उमेर के हो?",
        "किरायामा सम्झौता ढाँचा तयार गर्नुहोस्",
      ],
      followUpOptions: [
        "सरल रूपमा व्याख्या गर्नुहोस्",
        "पत्र तयार गर्नुहोस्",
        "सम्बन्धित कानून देखाउनुहोस्",
        "कानुनी सहयोग खोज्नुहोस्",
      ],
      helpButtons: {
        savedDocuments: "पुस्तिकाहरू",
        bookmarks: "बुकमार्क",
        settings: "सेटिङ्स",
      },
      actionPanel: {
        keyTakeaways: "मुख्य बुँदाहरू",
        relatedLaws: "सम्बन्धित कानूनहरू",
        recommendedDocuments: "सिफारिस गरिएको दस्तावेजहरू",
        legalAidContacts: "कानुनी सहायता सम्पर्कहरू",
        nextStep: "अर्को कदम",
      },
      panelLinks: {
        complaintLetter: "उद्देश्य पत्र",
        rentalAgreement: "किराया सम्झौता",
        findLawyer: "नजिकको वकिल खोज्नुहोस्",
      },
    },
    home: {
      hero: {
        badge: "एआई-समर्थित कानुनी मार्गदर्शन",
        title: "आफ्नो अधिकार जान्नुहोस्।",
        accent: "जीवनले सोध्नुअघि।",
        subtitle: "नेपाली कानूनलाई सादा भाषामा बुझ्नुहोस्। तत्काल उत्तर प्राप्त गर्नुहोस्, दस्तावेजहरू तयार गर्नुहोस्, र क्रियाशील कदमहरू लिनुहोस्।",
        startAI: "एआई सहायक सुरु गर्नुहोस्",
        explore: "कानुनी विषयहरू अन्वेषण गर्नुहोस्",
        joinCommunity: "समुदायमा सामेल हुनुहोस्",
        anonymousShield: "१००% गुमनाम",
        privateSecure: "गोपनीय र सुरक्षित",
        nepalSpecific: "नेपाल-विशिष्ट",
      },
      trustItems: [
        "एआई-समर्थित मार्गदर्शन",
        "महिला केन्द्रित",
        "गोपनीयता पहिलो",
        "नेपाल विशिष्ट",
        "कानुनी जानकारी",
        "दस्तावेज सहयोग",
      ],
      problem: {
        title: "कानुनी जानकारी बुझ्न वकिल चाहिन्छ भन्ने हुँदैन।",
        desc: "नेपालमा, धेरै महिलाहरूले आफ्नो कानुनी अधिकारहरू बुझ्न खोज्दा तीन अड्चनहरू भोग्छन्।",
        cards: [
          { title: "जटिल कानूनहरू", desc: "कानुनी कागजातहरू जटिल भाषामा लेखिएका छन् जुन व्यावसायिक सहयोगबिना नेभिगेट गर्न लगभग असम्भव छ।" },
          { title: "महंगो परामर्श", desc: "निजी वकिलहरू प्रति परामर्श NPR 1,000–5,000 लिन्छन् — धेरै नेपाली महिलाहरूका लागि पहुँच बाहिर।" },
          { title: "विश्वसनीय मार्गदर्शन छैन", desc: "न्यायोचित, कलंक, र गुमनाम स्रोतहरूको कमीले महिलाहरूलाई आवश्यक सहयोग खोज्नबाट रोक्छ।" },
        ],
      },
      topicsSection: {
        label: "कानुनी विषयहरू",
        title: "जीवनका प्रत्येक क्षेत्रमा आफ्नो अधिकार जान्नुहोस्",
      },
      faq: [
        { q: "के मेरो पहिचान सुरक्षित छ?", a: "अवश्य। Her Legal सँगको सबै अन्तर्क्रिया अनाम छन्। हामी व्यक्तिगत जानकारी सङ्कलन गर्दैनौं। तपाईंको गोपनीयता र सुरक्षा हाम्रो शीर्ष प्राथमिकता हो।" },
        { q: "म कानुनी सहायता कसरी पाउँ?", a: "हाम्रा एआई सहायकलाई सोधेर सुरु गर्नुहोस् — यो निःशुल्क र तत्काल छ। विशिष्ट कानुनी मार्गदर्शनका लागि, हामी तपाईंलाई हाम्रो कानुनी साझेदारहरूको नेटवर्कसँग जोड्न सक्छौं।" },
        { q: "के यो सेवा निःशुल्क छ?", a: "हो। हरेक सुविधा — एआई कानुनी सहायक, दस्तावेज ढाँचा, ज्ञान हब, र समुदाय समर्थन — पूर्ण रूपमा निःशुल्क छ।" },
        { q: "यदि मलाई तात्कालिक सहयोग चाहियो भने?", a: "यदि तपाईं तुरुन्तै खतरा मा हुनुहुन्छ भने, महिला हेल्पलाइन 1145 वा प्रहरी 100 मा फोन गर्नुहोस्। हाम्रो आपतकालीन अनुभागमा सबै नम्बरहरू छन्।" },
      ],
      reality: {
        label: "वास्तविकता",
        title: "नेपालमा धेरैजसो महिलाहरू कानुनी चुनौतीहरूको सामना एक्लै गर्न बाध्य छन्।",
        desc: "कानून यस्तो भाषामा लेखिएको छ जसलाई बुझ्न वर्षौं लाग्छ। वकिलहरूले धेरैजसोले बेहोर्न नसक्ने शुल्क लिन्छन्। र मद्दत माग्नुको अर्थ प्रायः न्यायोचित हुनु हो।",
        stat1: "नेपाली महिलाहरू आफ्नो कानुनी अधिकारबारे अनभिज्ञ छन्",
        stat2: "लागत वा न्यायोचितको डरले कहिल्यै कानुनी सहायता खोज्दैनन्",
      },
      ai: {
        headerTitle: "साथी — एआई कानुनी सहायक",
        online: "अनलाइन",
        welcomeMsg: "नेपाली कानूनको बारेमा जे पनि सोध्नुहोस्।",
        mockupQuestion: "सम्बन्ध विच्छेदको बेला मेरो अधिकार के-के हुन्?",
        mockupSource: "मुलुकी देवानी संहिता, २०७४",
        mockupItem1: "संयुक्त रूपमा आर्जित सम्पत्तिको बराबर विभाजन",
        mockupItem2: "यदि तपाईं आर्थिक रूपमा परनिर्भर हुनुहुन्छ भने गुजारा भत्ता",
        mockupItem3: "बालबालिकाको सर्वोत्तम हितको आधारमा अभिभावकत्व",
        mockupPlaceholder: "थप प्रश्न सोध्नुहोस्...",
        label: "एआई कानुनी सहायक",
        title: "तपाईं सोध्नुहुन्छ। यसले जवाफ दिन्छ। सादा भाषामा।",
        desc: "नेपालको संविधान, देवानी संहिता, श्रम ऐन र ३० भन्दा बढी कानुनी दस्तावेजहरूमा तालिम प्राप्त। तपाईंको व्यक्तिगत कानुनी मार्गदर्शक, जहिले पनि उपलब्ध, पूर्ण रूपमा निःशुल्क।",
        feature1: "तत्काल जवाफ, २४/७",
        feature2: "नेपाली र अंग्रेजी समर्थन",
        feature3: "हरेक दाबीको लागि स्रोत उद्धृत",
        feature4: "१००% गुमनाम",
        cta: "एआई सहायक प्रयोग गर्नुहोस्",
        saveAnswer: "जवाफ सुरक्षित गर्नुहोस्",
        generateDoc: "दस्तावेज बनाउनुहोस्",
        share: "सेयर गर्नुहोस्",
      },
      documents: {
        label: "दस्तावेज निर्माता",
        title: "एक क्लिक। कानुनी दस्तावेज। दायर गर्न तयार।",
        desc: "उजुरी पत्रदेखि शपथपत्रसम्म। साधारण प्रश्नहरूको जवाफ दिनुहोस्, र एआईले पूर्ण, उचित ढाँचामा कानुनी दस्तावेज तयार गर्छ।",
        type1: "उजुरी पत्र",
        type2: "कानुनी सूचना",
        type3: "शपथपत्र",
        type4: "सम्झौता",
        type5: "निवेदन",
        type6: "माग पत्र",
        cta: "दस्तावेज बनाउनुहोस्",
        previewTitle: "उजुरी पत्रको मस्यौदा",
        previewFootnote: "एआईद्वारा तयार — समीक्षा र डाउनलोड गर्न तयार",
      },
      knowledge: {
        label: "ज्ञान केन्द्र",
        title: "आफ्नो अधिकार जान्नुहोस्। आफ्नै समयमा।",
        searchPlaceholder: "लेखहरू खोज्नुहोस्...",
      },
      communitySection: {
        label: "समुदाय",
        stat: "महिलाहरू हाम्रो समुदायमा",
        title: "तपाईं एक्लो हुनुहुन्न। हजारौंले साझा गरेका छन्।",
        desc: "गुमनाम रूपमा साझा गर्न, प्रश्न सोध्न, र कानुनी चुनौतीहरूको सामना गरिरहेका अन्य महिलाहरूलाई समर्थन गर्न सुरक्षित स्थान। कुनै न्यायोचित होइन। केवल समझदारी।",
        cta: "समुदायमा सामेल हुनुहोस्",
      },
      stats: {
        activeUsers: "सक्रिय प्रयोगकर्ताहरू",
        aiAnswers: "एआई जवाफहरू",
        documentsGenerated: "दस्तावेज तयार",
        communityStories: "समुदाय कथाहरू",
      },
      emergency: {
        label: "तत्काल सहायता चाहियो?",
        title: "तपाईं एक्लो हुनुहुन्न। मद्दत एक फोनको दूरीमा छ।",
        desc: "निःशुल्क, गोपनीय समर्थन २४/७ उपलब्ध। तालिमप्राप्त पेशेवरहरू सुन्न तयार छन्।",
        womensHelpline: "महिला हेल्पलाइन",
        policeEmergency: "प्रहरी आपतकालीन",
        legalAid: "कानुनी सहायता आयोग",
      },
      trust: {
        label: "किन Her Legal",
        title: "विश्वासमा निर्मित। डिजाइनद्वारा ग्यारेन्टी।",
        feature1Title: "पूर्ण गुमनामता",
        feature1Desc: "कुनै व्यक्तिगत जानकारी आवश्यक छैन। तपाईंको पहिचान कहिल्यै भण्डारण वा साझा गरिँदैन।",
        feature2Title: "अन्त-देखि-अन्त गोपनीयता",
        feature2Desc: "सबै कुराकानी एन्क्रिप्टेड छन्। हामी तपाईंको डाटा ट्र्याक, लग वा बेच्दैनौं।",
        feature3Title: "नेपालको लागि बनाइएको",
        feature3Desc: "हरेक जवाफ वास्तविक नेपाली कानूनलाई सन्दर्भ गर्दछ। संविधानदेखि देवानी संहितासम्म।",
        feature4Title: "सबैको लागि निःशुल्क",
        feature4Desc: "सबै सुविधाहरू पूर्ण रूपमा निःशुल्क छन्। कुनै लुकेको शुल्क छैन, कुनै प्रिमियम स्तर छैन।",
        faqTitle: "सामान्य प्रश्नहरू",
        faq1Q: "के मेरो पहिचान साँच्चै सुरक्षित छ?",
        faq1A: "पूर्ण रूपमा। सबै अन्तर्क्रिया पूर्ण रूपमा गुमनाम छन्। हामी व्यक्तिगत जानकारी भण्डारण गर्दैनौं, र तपाईंको पहिचान अन्य प्रयोगकर्ताहरूलाई कहिल्यै खुलासा गरिँदैन।",
        faq2Q: "एआई कति सटीक छ?",
        faq2A: "हाम्रो एआई ३० भन्दा बढी नेपाली कानुनी पाठहरूमा तालिम प्राप्त छ जसमा संविधान, मुलुकी देवानी संहिता, श्रम ऐन, र घरेलु हिंसा ऐन समावेश छन्। महत्वपूर्ण निर्णयहरू सधैं योग्य वकिलसँग प्रमाणित गर्नुहोस्।",
        faq3Q: "के म साइट नेपालीमा प्रयोग गर्न सक्छु?",
        faq3A: "हो। प्लेटफर्मले अंग्रेजी र नेपाली दुवै भाषालाई समर्थन गर्दछ। कुनै पनि भाषामा प्रश्न सोध्नुहोस् र सोही भाषामा जवाफ प्राप्त गर्नुहोस्।",
      },
      cta: {
        title: "कानुनी मार्गदर्शन।",
        accent: "बुझ्न सकिने बनाइएको।",
        desc: "Her Legal बाट सुरु गर्नुहोस्। यो निःशुल्क, गुमनाम, र नेपालको हरेक महिलाको लागि बनाइएको छ।",
        cta: "सुरु गर्नुहोस्",
      },
    },
    aboutUs: {
      label: "हाम्रोबारे",
      title: "कानुनी सचेतनाबाट महिलाहरूलाई सशक्त बनाउँदै",
      desc: "Her Legal एक नेपालस्थित पहलकदमी हो जुन महिलाहरूलाई पहुँचयोग्य कानुनी जानकारी, आफ्नो कथाहरू साझा गर्न सुरक्षित समुदाय, र समय समयमा दयालु समर्थन प्रदान गर्न समर्पित छ।",
      cards: [
        { title: "हाम्रो उद्देश्य", desc: "शिक्षा, सामुदायिक समर्थन, र पहुँचयोग्य स्रोतहरूमार्फत नेपाली महिलाहरू र उनीहरूको कानुनी अधिकारहरूको बीचको दूरीलाई पुल गर्ने।" },
        { title: "हाम्रो दृष्टिकोण", desc: "एक नेपाल जहाँ हरेक महिला आफ्नो अधिकारहरूको बारेमा जानकार छ, बोल्न सक्षम छ, र न्यायतर्फको यात्रा मा समर्थित छ।" },
        { title: "हाम्रो मूल्यहरू", desc: "सुरक्षा, गोपनीयता, समानुभूति, र हरेक महिलाको गरिमा र कानुनी सुरक्षाप्रति अडिग विश्वास।" },
      ],
    },
    campaigns: {
      label: "कृयाशीलता",
      title: "अभियान र कार्यक्रमहरू",
      items: [
        { title: "आफ्नो अधिकार जान्नुहोस्", tag: "कार्यशाला", desc: "नेपालका सबै सात प्रदेशहरूमा निःशुल्क कानुनी साक्षरता कार्यशालाहरू, घरेलु हिंसा, सम्पत्ति अधिकार, र कार्यस्थल संरक्षणहरू समेटेर।" },
        { title: "सुरक्षित स्वर", tag: "अभियान", desc: "एक गुमनाम कथावाचन अभियान जसले महिलाहरूलाई आफ्ना अनुभवहरू साझा गर्न र समुदायमा एक अर्काबाट सहारा पाउन सशक्त बनाउँछ।" },
        { title: "साथी हेल्पलाइन", tag: "सेवा", desc: "कानुनी सल्लाहकार, परामर्शदाता, र आपतकालीन समर्थन सेवाहरू सँग महिलाहरूलाई गोपनीय रूपमा जोड्ने हेल्पलाइन।" },
      ],
    },
    contactHelp: {
      label: "सम्पर्कमा रहनुहोस्",
      title: "सम्पर्क र सहयोग",
      desc: "हामीलाई सम्पर्क गर्नुहोस्। चाहे तपाईंलाई कानुनी मार्गदर्शन चाहियो, आफ्नो कथा साझा गर्न चाहनुहुन्छ, वा केवल कसैसँग कुरा गर्न चाहानुहुन्छ — हामी यहाँ छौं।",
      emergencyTitle: "आपतकालीन हेल्पलाइनहरू",
      emailTitle: "हामीलाई इमेल गर्नुहोस्",
      generalInquiry: "सामान्य सोधपुछका लागि:",
      email: "hello@herlegal.org",
      followTitle: "हामीलाई फलो गर्नुहोस्",
      socials: ["Facebook", "Instagram", "Twitter"],
    },
    confessions: {
      label: "आफ्नो कथा साझा गर्नुहोस्",
      title: "तिम्रो आवाज, तिम्रो सत्य",
      desc: "आफ्ना अनुभवहरू अनाम रूपमा साझेदार गर्नुहोस्। तपाईं एक्लो हुनुहुन्न।",
      placeholder: "तिमी के साझा गर्न चाहन्छौ?",
      anonymous: "गुमनाम रूपमा पोस्ट गर्नुहोस्",
      posting: "पद प्रवेश गर्दै...",
      share: "शेयर →",
      anonymousAuthor: "अनाम",
      replyPlaceholder: "उत्तर लेख्नुहोस्...",
      reply: "उत्तर",
    },
    news: {
      label: "अपडेटहरू",
      title: "समाचार र पत्रिका",
      articles: [
        { title: "प्रदेश २ मा नयाँ कानुनी सहायता केन्द्रहरू खुल्दैछन्", date: "जुन २८, २०८३", excerpt: "प्रदेश २ भरमा महिला ग्रामीण क्षेत्रहरूका लागि निःशुल्क कानुनी परामर्श प्रदान गर्न पाँच नयाँ कानुनी सहायता केन्द्रहरू खुल्दैछन्।" },
        { title: "घरेलु हिंसा कानून संशोधन: तपाईंले जान्नु पर्ने कुरा", date: "जुन १५, २०८३", excerpt: "घरेलु हिंसा कानूनमा हालैका संशोधनहरूले पीडितहरूको सुरक्षालाई सुदृढ पार्दछन्। यहाँ सरल भाषा मा यसको संक्षिप्त विवरण छ।" },
        { title: "Her Legal ले ५०० महिलासम्म सहयोग पुर्‍याउने माइलस्टोन छुनुहोस्", date: "मे ३०, २०८३", excerpt: "हामी विनम्रतापूर्वक साझा गर्न चाहन्छौं कि Her Legal ले अब नेपालभरि ५०० भन्दा बढी महिलाहरूसँग कानुनी मार्गदर्शन र समर्थन प्रदान गरेको छ।" },
      ],
    },
    team: {
      label: "व्यक्ति",
      title: "हाम्रो टोली",
      members: [
        { name: "आराी गुरुङ", role: "", initials: "AG" },
        { name: "दलसारा सोती मगर", role: "", initials: "DSM" },
        { name: "नन्दानी सेवा", role: "", initials: "NS" },
        { name: "सोफिया कुँवर", role: "", initials: "SK" },
      ],
    },
    notFound: {
      title: "पृष्ठ भेटिएन",
      desc: "तपाईं खोजिरहनुभएको पृष्ठ अस्तित्वमा छैन वा सारिएको छ।",
      goHome: "गृहमा जानुहोस्",
    },
    common: {
      justNow: "अहिले",
      mAgo: "मिनेट अघि",
      hAgo: "घण्टा अघि",
      dAgo: "दिन अघि",
      anonymous: "अनाम",
      loading: "लोड हुँदैछ...",
      saving: "सुरक्षित गर्दै...",
      save: "सुरक्षित गर्नुहोस्",
      saved: "सुरक्षित गरियो",
      delete: "मेट्नुहोस्",
      report: "रिपोर्ट गर्नुहोस्",
      share: "सेयर गर्नुहोस्",
      cancel: "रद्द गर्नुहोस्",
      confirm: "पुष्टि गर्नुहोस्",
      back: "पछाडि",
      continue: "जारी राख्नुहोस्",
      search: "खोज्नुहोस्",
      noResults: "कुनै नतिजा फेला परेन",
      error: "केही गलत भयो। कृपया फेरि प्रयास गर्नुहोस्।",
      success: "सफल",
      dashboard: "ड्यासबोर्ड",
      settings: "सेटिङ्स",
      notifications: "सूचनाहरू",
      profile: "प्रोफाइल",
      security: "सुरक्षा",
      signOut: "साइन आउट",
      backToSite: "साइटमा फर्कनुहोस्",
    },
    community: {
      title: "समुदाय",
      subtitle: "सेयर गर्नुहोस्, सिक्नुहोस्, र एक अर्कालाई समर्थन गर्नुहोस् — तपाईं चाहनुहुन्छ भने गुमनाम रूपमा।",
      shareStory: "आफ्नो कथा सेयर गर्नुहोस्",
      createPost: "पोस्ट बनाउनुहोस्",
      latest: "नयाँ",
      trending: "ट्रेन्डिङ",
      loadingPosts: "पोस्टहरू लोड हुँदैछन्...",
      noPosts: "अहिलेसम्म कुनै पोस्ट छैन",
      noPostsDesc: "यस श्रेणीमा पहिलो कथा सेयर गर्ने व्यक्ति बन्नुहोस्।",
      all: "सबै",
      womenRights: "महिला अधिकार",
      employment: "रोजगारी",
      marriage: "विवाह",
      property: "सम्पत्ति",
      domesticViolence: "घरेलु हिंसा",
      cyberCrime: "साइबर अपराध",
      citizenship: "नागरिकता",
      familyLaw: "पारिवारिक कानून",
      general: "सामान्य",
      anonymousNames: ["गुमनाम कमल", "गुमनाम आशा", "गुमनाम नागरिक", "गुमनाम भँगेरा", "गुमनाम सुनाखरी", "गुमनाम नदी"],
    },
    createPost: {
      back: "समुदायमा फर्कनुहोस्",
      anonymousHint: "तपाईंको पहिचान लुकेको छ। कसैले तपाईंको नाम देख्ने छैन।",
      publicHint: "यो पोस्टले तपाईंको प्रयोगकर्ता नाम देखाउनेछ।",
      anonymous: "गुमनाम",
      public: "सार्वजनिक",
      title: "आफ्नो कथा सेयर गर्नुहोस्",
      subtitle: "तपाईंको आवाज महत्त्वपूर्ण छ। गुमनाम वा सार्वजनिक रूपमा सेयर गर्नुहोस्।",
      titleLabel: "शीर्षक",
      titlePlaceholder: "तपाईंको मनमा के छ?",
      categoryLabel: "श्रेणी",
      storyLabel: "तपाईंको कथा",
      storyPlaceholder: "आफ्नो अनुभव सेयर गर्नुहोस्, सल्लाह माग्नुहोस्, वा छलफल सुरु गर्नुहोस्...",
      charCount: "/१००००",
      tagsLabel: "ट्यागहरू (वैकल्पिक, अल्पविरामले छुट्याइएको)",
      tagsPlaceholder: "जस्तै: कार्यस्थल, उत्पीडन, सल्लाह",
      posting: "पोस्ट गर्दै...",
      submit: "समुदायसँग सेयर गर्नुहोस्",
      validationError: "शीर्षक र पाठ आवश्यक छ",
      apiError: "पोस्ट सिर्जना गर्न असफल",
    },
    postDetail: {
      community: "समुदाय",
      helpful: "सहयोगी",
      supportive: "समर्थन",
      insightful: "अन्तर्दृष्टिपूर्ण",
      comments: "टिप्पणीहरू",
      commentPlaceholder: "आफ्नो विचार सेयर गर्नुहोस्...",
      postAnonymous: "गुमनाम रूपमा पोस्ट गर्नुहोस्",
      send: "पठाउनुहोस्",
      signInToComment: "टिप्पणी गर्न साइन इन गर्नुहोस्",
      noComments: "अहिलेसम्म कुनै टिप्पणी छैन। पहिलो टिप्पणी गर्नुहोस्।",
      reportPlaceholder: "तपाईं यो किन रिपोर्ट गर्दै हुनुहुन्छ? (आवश्यक)",
      submitReport: "रिपोर्ट पठाउनुहोस्",
      deleteConfirm: "यो पोस्ट मेट्ने?",
      saves: "पुस्तिकाहरू",
    },
    dashboard: {
      title: "ड्यासबोर्ड",
      overview: "सिंहावलोकन",
      activity: "गतिविधि",
      aiConversations: "एआई कुराकानी",
      savedDocuments: "सुरक्षित कागजातहरू",
      bookmarks: "बुकमार्क",
      communityPosts: "समुदाय पोस्टहरू",
      quickActions: "द्रुत कार्यहरू",
      askAI: "एआई सहायकलाई सोध्नुहोस्",
      generateDoc: "कागजात बनाउनुहोस्",
      community: "समुदाय",
      legalDocuments: "कानुनी कागजातहरू",
      legalGlossary: "कानुनी शब्दकोष",
      recentActivity: "हालैको गतिविधि",
      noActivity: "कुनै हालैको गतिविधि छैन",
      activityTabDesc: "प्लेटफर्ममा तपाईंको हालैको गतिविधि।",
      noActivityDesc: "अहिलेसम्म कुनै गतिविधि छैन। एआई सहायकसँग कुरा गरेर वा समुदाय अन्वेषण गरेर सुरु गर्नुहोस्।",
      startChatting: "कुराकानी सुरु गर्नुहोस्",
      settingsTabDesc: "आफ्नो खाता सेटिङ्स व्यवस्थापन गर्नुहोस्।",
      accountCreated: "खाता सिर्जना गरियो",
      welcome: "स्वागत छ,",
      welcomeSub: "तपाईंको खातामा के हुँदैछ यहाँ हेर्नुहोस्।",
      profileCard: "प्रोफाइल",
      profileCardDesc: "आफ्नो नाम, इमेल र फोटो अपडेट गर्नुहोस्",
      securityCard: "सुरक्षा",
      securityCardDesc: "पासवर्ड र प्रमाणीकरण",
      notificationsCard: "सूचनाहरू",
      notificationsCardDesc: "सूचना प्राथमिकताहरू व्यवस्थापन गर्नुहोस्",
    },
    settingsProfile: {
      title: "प्रोफाइल",
      subtitle: "आफ्नो व्यक्तिगत जानकारी अपडेट गर्नुहोस्।",
      email: "इमेल",
      username: "प्रयोगकर्ता नाम",
      phone: "फोन",
      saveChanges: "परिवर्तन सुरक्षित गर्नुहोस्",
      profileUpdated: "प्रोफाइल अपडेट गरियो",
      updateFailed: "अपडेट असफल",
    },
    settingsSecurity: {
      title: "सुरक्षा",
      subtitle: "आफ्नो पासवर्ड परिवर्तन गर्नुहोस्।",
      currentPassword: "हालको पासवर्ड",
      newPassword: "नयाँ पासवर्ड",
      passwordPlaceholder: "कम्तीमा ६ क्यारेक्टर",
      confirmPassword: "नयाँ पासवर्ड पुष्टि गर्नुहोस्",
      changePassword: "पासवर्ड परिवर्तन गर्नुहोस्",
      passwordsMismatch: "पासवर्डहरू मेल खाँदैनन्",
      passwordChanged: "पासवर्ड सफलतापूर्वक परिवर्तन गरियो",
      changeFailed: "पासवर्ड परिवर्तन गर्न असफल",
    },
    settingsNotifications: {
      title: "सूचनाहरू",
      subtitle: "आफ्नो सूचना प्राथमिकताहरू व्यवस्थापन गर्नुहोस्।",
      replies: "जवाफहरू",
      repliesDesc: "तपाईंको पोस्टमा कसैले जवाफ दिँदा सूचित गर्नुहोस्",
      communityActivity: "समुदाय गतिविधि",
      communityActivityDesc: "समुदाय गतिविधिमा अद्यावधिक रहनुहोस्",
      legalUpdates: "कानुनी अद्यावधिकहरू",
      legalUpdatesDesc: "नेपाली कानून परिवर्तनहरूको बारेमा अद्यावधिकहरू प्राप्त गर्नुहोस्",
      savePreferences: "प्राथमिकताहरू सुरक्षित गर्नुहोस्",
      preferencesSaved: "प्राथमिकताहरू सुरक्षित गरियो",
    },
    documents: {
      title: "कानुनी कागजातहरू",
      subtitle: "कानुनी कागजातहरू बनाउनुहोस्, सुरक्षित गर्नुहोस्, र डाउनलोड गर्नुहोस्।",
      templates: "टेम्प्लेटहरू",
      documentTemplates: "कागजात टेम्प्लेटहरू",
      savedDocuments: "सुरक्षित कागजातहरू",
      noSaved: "अहिलेसम्म कुनै कागजात सुरक्षित गरिएको छैन। माथि एउटा बनाउनुहोस्।",
      generate: "कागजात बनाउनुहोस्",
      generating: "बनाउँदै...",
      editForm: "फारम सम्पादन गर्नुहोस्",
      download: "डाउनलोड",
      generationFailed: "कागजात बनाउन असफल",
      saveFailed: "सुरक्षित गर्न असफल",
      deleteConfirm: "यो कागजात मेट्ने?",
      complaintLetter: "उजुरी पत्र",
      legalNotice: "कानुनी सूचना",
      affidavit: "हलफनामा",
      agreement: "सम्झौता",
      application: "निवेदन",
      demandLetter: "माग पत्र",
    },
    glossary: {
      title: "कानुनी शब्दकोष",
      subtitle: "सामान्य नेपाली कानुनी शब्दहरू सरल भाषामा व्याख्या गरिएको।",
      searchPlaceholder: "शब्द वा परिभाषा खोज्नुहोस्...",
      terms: "शब्दहरू",
      courtProcedure: "अदालत प्रक्रिया",
      familyLaw: "पारिवारिक कानून",
      criminalLaw: "फौजदारी कानून",
      propertyLaw: "सम्पत्ति कानून",
      civilLaw: "सिभिल कानून",
      constitutionalLaw: "संवैधानिक कानून",
      intellectualProperty: "बौद्धिक सम्पत्ति",
      employmentLaw: "रोजगार कानून",
      disputeResolution: "विवाद समाधान",
      immigration: "अध्यागमन",
    },
    notificationsPage: {
      title: "सूचनाहरू",
      markAllRead: "सबै पढिएको चिन्ह लगाउनुहोस्",
      clearAll: "सबै हटाउनुहोस्",
      empty: "अहिलेसम्म कुनै सूचना छैन",
      confirmClear: "के तपाई सबै सूचनाहरू हटाउन निश्चित हुनुहुन्छ? यो कार्य पूर्ववत गर्न सकिंदैन।",
    },
    onboarding: {
      step0Title: "आफ्नो भाषा छान्नुहोस्",
      step0Desc: "प्लेटफर्मको लागि आफ्नो मनपर्ने भाषा चयन गर्नुहोस्।",
      english: "English",
      nepali: "नेपाली",
      step1Title: "तपाईंलाई केमा रुचि छ?",
      step1Desc: "तपाईं सिक्न चाहनुहुने विषयहरू छान्नुहोस्। यी पछि परिवर्तन गर्न सक्नुहुन्छ।",
      step2Title: "समुदाय प्राथमिकताहरू",
      step2Desc: "आफ्नो समुदाय अनुभव अनुकूलित गर्नुहोस्।",
      anonymousPosting: "गुमनाम पोस्टिङ",
      anonymousPostingDesc: "तपाईंको पहिचान सार्वजनिकबाट लुकेको छ",
      receiveReplies: "जवाफहरू प्राप्त गर्नुहोस्",
      receiveRepliesDesc: "तपाईंको पोस्टमा कसैले जवाफ दिँदा सूचित गर्नुहोस्",
      receiveNotifications: "सूचनाहरू प्राप्त गर्नुहोस्",
      receiveNotificationsDesc: "समुदाय गतिविधिमा अद्यावधिक रहनुहोस्",
      legalUpdates: "कानुनी अद्यावधिकहरू",
      legalUpdatesDesc: "नेपाली कानून परिवर्तनहरूको बारेमा अद्यावधिकहरू प्राप्त गर्नुहोस्",
      step3Title: "तपाईंको गोपनीयता महत्त्वपूर्ण छ",
      step3Desc: "हामी Her Legal मा तपाईंलाई कसरी सुरक्षित गर्छौं यहाँ छ।",
      privacyBullet1: "तपाईंको पहिचान सार्वजनिकबाट लुकेको छ",
      privacyBullet2: "केवल अधिकृत मध्यस्थकर्ताहरूले दुरुपयोगको अनुसन्धान गर्न सक्छन्",
      privacyBullet3: "तपाईंको कागजात र कुराकानीहरू निजी छन्",
      privacyBullet4: "तपाईंले प्रत्येक पोस्ट गुमनाम वा सार्वजनिक हो भनेर नियन्त्रण गर्नुहुन्छ",
      ready: "तपाईं तयार हुनुहुन्छ! सुरु गरौं।",
      goToDashboard: "ड्यासबोर्डमा जानुहोस्",
    },
  },
};

const STORAGE_KEY = "herlegal_language";

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    if (typeof window === "undefined") return "en";
    const saved = window.localStorage.getItem(STORAGE_KEY);
    return saved === "ne" ? "ne" : "en";
  });

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, lang);
    document.documentElement.lang = lang === "ne" ? "ne" : "en";
    document.documentElement.dir = "ltr";
  }, [lang]);

  const value = useMemo(() => ({
    lang,
    setLanguage: setLang,
    t: (key) => {
      const parts = key.split(".");
      return parts.reduce((obj, part) => obj?.[part], translations[lang]) ?? key;
    },
    translations: translations[lang],
  }), [lang]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
