import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LanguageContext = createContext(null);

const translations = {
  en: {
    navbar: {
      home: "Home",
      aiChat: "AI Chat",
      solutions: "Solutions",
      resources: "Resources",
      news: "News",
      about: "About",
      contact: "Contact",
      startFree: "Start Free",
      login: "Login",
      logout: "Logout",
      search: "Search",
      selectLanguage: "Language",
    },
    auth: {
      welcomeBack: "Welcome back",
      createAccount: "Create account",
      signInDesc: "Sign in to save your conversations.",
      joinDesc: "Join Her Legal anonymously.",
      username: "Username",
      email: "Email",
      phone: "Phone",
      password: "Password",
      pleaseWait: "Please wait...",
      signIn: "Sign In",
      createAccountBtn: "Create Account",
      dontHaveAccount: "Don't have an account?",
      alreadyHaveAccount: "Already have an account?",
      signUp: "Sign up",
      signInAction: "Sign in",
    },
    footer: {
      platform: "Platform",
      company: "Company",
      support: "Support",
      aiAssistant: "AI Assistant",
      legalTopics: "Legal Topics",
      documents: "Documents",
      knowledgeHub: "Knowledge Hub",
      about: "About",
      contact: "Contact",
      privacy: "Privacy",
      terms: "Terms",
      helpline: "Helpline",
      faq: "FAQ",
      safety: "Safety",
      description: "Making legal information accessible, understandable, and actionable for every woman in Nepal.",
      description: "Making legal information accessible, understandable, and actionable for every woman in Nepal.",
      rightsReserved: "All rights reserved.",
      builtWith: "Built with ❤️ for every woman in Nepal",
    },
    chatbotWidget: {
      title: "Saathi — Here to help",
      greet: "Hi, I'm here to help with questions about your rights. Ask me anything.",
      placeholder: "Type your question...",
      send: "Send",
      thinking: "Thinking...",
      error: "Something went wrong. Please try again.",
      noResponse: "No response",
      toggleNepali: "नेपाली",
      toggleEnglish: "English",
    },
    chatPage: {
      title: "Saathi AI",
      newConversation: "New Conversation",
      recent: "Recent",
      loading: "Loading...",
      noConversations: "No conversations yet",
      conversation: "Conversation",
      savedDocuments: "Saved Documents",
      bookmarks: "Bookmarks",
      settings: "Settings",
      emergencyHelp: "Emergency Help",
      welcomeBadge: "AI Legal Assistant",
      welcomeTitle: "Know your rights.",
      welcomeAccent: "Before life asks.",
      welcomeSub: "Ask anything about women's legal rights in Nepal. Free, anonymous, private.",
      promptHint: "Ask about your legal rights...",
      noMessages: "Ask something to start your conversation.",
      you: "You",
      assistant: "Saathi",
      needHelp: "Need Immediate Help?",
      legalGuidance: "This is general legal guidance and not legal advice. Consult a qualified lawyer for your specific situation.",
      categories: [
        { title: "Property Rights", prompt: "What are my property rights in Nepal?" },
        { title: "Employment", prompt: "What are my workplace rights in Nepal?" },
        { title: "Marriage & Divorce", prompt: "How do I file for divorce in Nepal?" },
        { title: "Domestic Violence", prompt: "How to report domestic violence in Nepal?" },
        { title: "Women's Rights", prompt: "What are women's constitutional rights in Nepal?" },
        { title: "Citizenship", prompt: "Explain citizenship laws in Nepal" },
        { title: "Cyber Crime", prompt: "How to report cyber crime in Nepal?" },
        { title: "Police & FIR", prompt: "How do I file a police complaint in Nepal?" },
      ],
      promptIdeas: [
        "Can my employer fire me without notice?",
        "Explain divorce procedures in Nepal",
        "What is the legal age for marriage?",
        "Create a rental agreement template",
      ],
      followUpOptions: [
        "Explain Simply",
        "Generate Letter",
        "Show Related Laws",
        "Find Legal Aid",
      ],
      helpButtons: {
        savedDocuments: "Saved Documents",
        bookmarks: "Bookmarks",
        settings: "Settings",
      },
      actionPanel: {
        keyTakeaways: "Key Takeaways",
        relatedLaws: "Related Laws",
        recommendedDocuments: "Recommended Documents",
        legalAidContacts: "Legal Aid Contacts",
        nextStep: "Next Step",
      },
      panelLinks: {
        complaintLetter: "Complaint Letter",
        rentalAgreement: "Rental Agreement",
        findLawyer: "Find Nearby Lawyer",
      },
    },
    home: {
      hero: {
        badge: "AI-Powered Legal Guidance",
        title: "Know your rights.",
        accent: "Before life asks.",
        subtitle: "Understand Nepali law in plain language. Get instant answers, generate documents, and take action — all in one place.",
        startAI: "Start AI Assistant",
        explore: "Explore Legal Topics",
      },
      trustItems: [
        "AI-Powered Guidance",
        "Women Focused",
        "Privacy First",
        "Nepal Specific",
        "Legal Information",
        "Document Assistance",
      ],
      problem: {
        title: "Legal information shouldn't require a lawyer to understand.",
        desc: "In Nepal, most women face three barriers when trying to understand their legal rights.",
        cards: [
          { title: "Confusing Laws", desc: "Legal documents are written in complex language that's nearly impossible to navigate without professional help." },
          { title: "Expensive Consultations", desc: "Private lawyers charge NPR 1,000–5,000 per consultation — out of reach for most Nepali women." },
          { title: "No Trusted Guidance", desc: "Fear of judgment, stigma, and lack of anonymous resources keep women from seeking the help they need." },
        ],
      },
      topicsSection: {
        label: "Legal Topics",
        title: "Know your rights, across every area of life",
      },
      faq: [
        { q: "Is my identity protected?", a: "Absolutely. All interactions with Her Legal are anonymous. We don't collect personal information. Your privacy and safety are our top priorities." },
        { q: "How do I get legal help?", a: "Start by asking our AI assistant below — it's free and instant. For specific legal guidance, we can connect you with our network of legal partners through the Contact page." },
        { q: "Is this service free?", a: "Yes. Every feature — AI legal assistant, document templates, knowledge hub, and community support — is completely free." },
        { q: "What if I need emergency help?", a: "If you're in immediate danger, call the Women's Helpline at 1145 or Police at 100. Our Emergency section has all the numbers." },
      ],
    },
    aboutUs: {
      label: "About Us",
      title: "Empowering women through legal awareness",
      desc: "Her Legal is a Nepal-based initiative dedicated to providing women with accessible legal information, a safe community to share their stories, and compassionate support when they need it most.",
      cards: [
        { title: "Our Mission", desc: "To bridge the gap between Nepali women and their legal rights through education, community support, and accessible resources." },
        { title: "Our Vision", desc: "A Nepal where every woman is informed of her rights, empowered to speak up, and supported in her journey toward justice." },
        { title: "Our Values", desc: "Safety, confidentiality, empathy, and unwavering belief in every woman's right to dignity and legal protection." },
      ],
    },
    campaigns: {
      label: "Take Action",
      title: "Campaigns & Programs",
      items: [
        { title: "Know Your Rights", tag: "Workshop", desc: "Free legal literacy workshops across all seven provinces of Nepal, covering domestic violence, property rights, and workplace protections." },
        { title: "Safe Voices", tag: "Campaign", desc: "An anonymous storytelling campaign that empowers women to share their experiences and find solidarity in community." },
        { title: "Sathi Helpline", tag: "Service", desc: "A confidential helpline connecting women with legal advisors, counselors, and emergency support services." },
      ],
    },
    contactHelp: {
      label: "Get in Touch",
      title: "Contact & Help",
      desc: "Reach out to us. Whether you need legal guidance, want to share your story, or just need someone to listen — we're here.",
      emergencyTitle: "Emergency Helplines",
      emailTitle: "Email Us",
      generalInquiry: "For general inquiries:",
      email: "hello@herlegal.org",
      followTitle: "Follow Us",
      socials: ["Facebook", "Instagram", "Twitter"],
    },
    confessions: {
      label: "Share Your Story",
      title: "Your voice, your truth",
      desc: "Share your experience anonymously. You are not alone.",
      placeholder: "What would you like to share?",
      anonymous: "Post anonymously",
      posting: "Posting...",
      share: "Share →",
      anonymousAuthor: "Anonymous",
      replyPlaceholder: "Write a reply...",
      reply: "Reply",
    },
    news: {
      label: "Updates",
      title: "News & Magazines",
      articles: [
        { title: "New Legal Aid Centers Opening in Province 2", date: "Jun 28, 2026", excerpt: "Five new legal aid centers are opening across Province 2 to provide free legal counsel to women in rural areas." },
        { title: "Domestic Violence Law Amendments: What You Need to Know", date: "Jun 15, 2026", excerpt: "Recent amendments to domestic violence laws strengthen protections for survivors. Here's a plain-language breakdown." },
        { title: "Her Legal Reaches 500 Women Helped Milestone", date: "May 30, 2026", excerpt: "We're humbled to share that Her Legal has now supported over 500 women across Nepal with legal guidance and support." },
      ],
    },
    team: {
      label: "People",
      title: "Our Team",
      members: [
        { name: "Aarati Gurung", role: "", initials: "AG" },
        { name: "Dalsara Soti Magar", role: "", initials: "DSM" },
        { name: "Nandani Sewa", role: "", initials: "NS" },
        { name: "Sofiya Kunwar", role: "", initials: "SK" },
      ],
    },
    notFound: {
      title: "Page not found",
      desc: "The page you're looking for doesn't exist or has been moved.",
      goHome: "Go Home",
    },
  },
  ne: {
    navbar: {
      home: "गृह",
      aiChat: "एआई कुराकानी",
      solutions: "समाधान",
      resources: "स्रोतहरू",
      news: "समाचार",
      about: "हाम्रोबारे",
      contact: "सम्पर्क",
      startFree: "निशुल्क सुरु गर्नुहोस्",
      login: "लगइन",
      logout: "लगआउट",
      search: "खोज्नुहोस्",
      selectLanguage: "भाषा",
    },
    auth: {
      welcomeBack: "पुन: स्वागत",
      createAccount: "खाता सिर्जना गर्नुहोस्",
      signInDesc: "तपाईंका संवादहरू बचत गर्न साइन इन गर्नुहोस्।",
      joinDesc: "Her Legal मा अनाम रुपमा सामेल हुनुहोस्।",
      username: "प्रयोगकर्ता नाम",
      email: "इमेल",
      phone: "फोन",
      password: "पासवर्ड",
      pleaseWait: "कृपया पर्खनुहोस्...",
      signIn: "साइन इन",
      createAccountBtn: "खाता सिर्जना गर्नुहोस्",
      dontHaveAccount: "खाता छैन?",
      alreadyHaveAccount: "पहिले नै खाता छ?",
      signUp: "साइन अप",
      signInAction: "साइन इन",
    },
    footer: {
      platform: "प्लेटफर्म",
      company: "कम्पनी",
      support: "समर्थन",
      aiAssistant: "एआई सहायक",
      legalTopics: "कानुनी विषयहरू",
      documents: "कागजातहरू",
      knowledgeHub: "ज्ञान हब",
      about: "हाम्रोबारे",
      contact: "सम्पर्क",
      privacy: "गोपनीयता",
      terms: "सर्तहरू",
      helpline: "हेल्पलाइन",
      faq: "FAQ",
      safety: "सुरक्षा",
      rightsReserved: "सबै अधिकार सुरक्षित छन्।",
      builtWith: "नेपालका हरेक महिलाका लागि बनाइयो",
    },
    chatbotWidget: {
      title: "Saathi — सहयोगका लागि तयार",
      greet: "नमस्ते, म तपाईंको अधिकारसम्बन्धी प्रश्नमा सहयोग गर्न यहाँ छु।",
      placeholder: "आफ्नो प्रश्न लेख्नुहोस्...",
      send: "पठाउनुहोस्",
      thinking: "सोच्दैछ...",
      error: "केही गलत भयो। कृपया फेरि प्रयास गर्नुहोस्।",
      noResponse: "उत्तर छैन",
      toggleNepali: "नेपाली",
      toggleEnglish: "English",
    },
    chatPage: {
      title: "Saathi AI",
      newConversation: "नयाँ संवाद",
      recent: "हालैका",
      loading: "लोड हुँदैछ...",
      noConversations: "अहिले कुनै संवाद छैन",
      conversation: "संवाद",
      savedDocuments: "पुस्तिकाहरू",
      bookmarks: "बुकमार्क",
      settings: "सेटिङ्स",
      emergencyHelp: "आपतकालीन सहयोग",
      welcomeBadge: "एआई कानुनी सहायक",
      welcomeTitle: "आफ्नो अधिकारहरु जान्नुहोस्।",
      welcomeAccent: "जीवनले सोध्नुअघि।",
      welcomeSub: "नेपालमा महिलासम्बन्धी कानुनी अधिकारहरू बारे केही सोध्नुहोस्। निःशुल्क, अनाम, निजी।",
      promptHint: "आफ्नो कानुनी अधिकारहरू बारे सोध्नुहोस्...",
      noMessages: "तपाईंको संवाद सुरु गर्न केही सोध्नुहोस्।",
      you: "तपाईं",
      assistant: "Saathi",
      needHelp: "तत्काल सहयोग चाहियो?",
      legalGuidance: "यो सामान्य कानुनी मार्गदर्शन हो र कानुनी सल्लाह होइन। तपाईंको विशेष परिस्थितिका लागि योग्य वकिलसँग परामर्श गर्नुहोस्।",
      categories: [
        { title: "संपत्ति अधिकार", prompt: "नेपालमा मेरा सम्पत्ति अधिकारहरू के हुन्?" },
        { title: "रोजगारी", prompt: "मेरा कार्यस्थल अधिकारहरू के हुन्?" },
        { title: "विवाह र डिभोर्स", prompt: "नेपालमा विभाजन कसरी दायर गर्ने?" },
        { title: "घरेलु हिंसा", prompt: "नेपालमा घरेलु हिंसा कसरी रिपोर्ट गर्ने?" },
        { title: "महिलाका अधिकार", prompt: "नेपालमा महिलाका संवैधानिक अधिकारहरू के हुन्?" },
        { title: "नागरिकता", prompt: "नेपालको नागरिकता कानून व्याख्या गर्नुहोस्" },
        { title: "साइबर अपराध", prompt: "नेपालमा साइबर अपराध कसरी रिपोर्ट गर्ने?" },
        { title: "प्रहरी र एफआईआर", prompt: "नेपालमा प्रहरी उजुरी कसरी दायर गर्ने?" },
      ],
      promptIdeas: [
        "के मेरो नियोक्ताले सूचना बिना मलाई हटाउन सक्छ?",
        "नेपालमा विभाजन प्रक्रिया स्पष्टीकरण गर्नुहोस्",
        "विवाहको कानुनी उमेर के हो?",
        "किरायामा सम्झौता ढाँचा तयार गर्नुहोस्",
      ],
      followUpOptions: [
        "सरल रूपमा व्याख्या गर्नुहोस्",
        "पत्र तयार गर्नुहोस्",
        "सम्बन्धित कानून देखाउनुहोस्",
        "कानुनी सहयोग खोज्नुहोस्",
      ],
      helpButtons: {
        savedDocuments: "पुस्तिकाहरू",
        bookmarks: "बुकमार्क",
        settings: "सेटिङ्स",
      },
      actionPanel: {
        keyTakeaways: "मुख्य बुँदाहरू",
        relatedLaws: "सम्बन्धित कानूनहरू",
        recommendedDocuments: "सिफारिस गरिएको दस्तावेजहरू",
        legalAidContacts: "कानुनी सहायता सम्पर्कहरू",
        nextStep: "अर्को कदम",
      },
      panelLinks: {
        complaintLetter: "उद्देश्य पत्र",
        rentalAgreement: "किराया सम्झौता",
        findLawyer: "नजिकको वकिल खोज्नुहोस्",
      },
    },
    home: {
      hero: {
        badge: "एआई-समर्थित कानुनी मार्गदर्शन",
        title: "आफ्नो अधिकार जान्नुहोस्।",
        accent: "जीवनले सोध्नुअघि।",
        subtitle: "नेपाली कानूनलाई सादा भाषामा बुझ्नुहोस्। तत्काल उत्तर प्राप्त गर्नुहोस्, दस्तावेजहरू तयार गर्नुहोस्, र क्रियाशील कदमहरू लिनुहोस्।",
        startAI: "एआई सहायक सुरु गर्नुहोस्",
        explore: "कानुनी विषयहरू अन्वेषण गर्नुहोस्",
      },
      trustItems: [
        "एआई-समर्थित मार्गदर्शन",
        "महिला केन्द्रित",
        "गोपनीयता पहिलो",
        "नेपाल विशिष्ट",
        "कानुनी जानकारी",
        "दस्तावेज सहयोग",
      ],
      problem: {
        title: "कानुनी जानकारी बुझ्न वकिल चाहिन्छ भन्ने हुँदैन।",
        desc: "नेपालमा, धेरै महिलाहरूले आफ्नो कानुनी अधिकारहरू बुझ्न खोज्दा तीन अड्चनहरू भोग्छन्।",
        cards: [
          { title: "जटिल कानूनहरू", desc: "कानुनी कागजातहरू जटिल भाषामा लेखिएका छन् जुन व्यावसायिक सहयोगबिना नेभिगेट गर्न लगभग असम्भव छ।" },
          { title: "महंगो परामर्श", desc: "निजी वकिलहरू प्रति परामर्श NPR 1,000–5,000 लिन्छन् — धेरै नेपाली महिलाहरूका लागि पहुँच बाहिर।" },
          { title: "विश्वसनीय मार्गदर्शन छैन", desc: "न्यायोचित, कलंक, र गुमनाम स्रोतहरूको कमीले महिलाहरूलाई आवश्यक सहयोग खोज्नबाट रोक्छ।" },
        ],
      },
      topicsSection: {
        label: "कानुनी विषयहरू",
        title: "जीवनका प्रत्येक क्षेत्रमा आफ्नो अधिकार जान्नुहोस्",
      },
      faq: [
        { q: "के मेरो पहिचान सुरक्षित छ?", a: "अवश्य। Her Legal सँगको सबै अन्तर्क्रिया अनाम छन्। हामी व्यक्तिगत जानकारी सङ्कलन गर्दैनौं। तपाईंको गोपनीयता र सुरक्षा हाम्रो शीर्ष प्राथमिकता हो।" },
        { q: "म कानुनी सहायता कसरी पाउँ?", a: "हाम्रा एआई सहायकलाई सोधेर सुरु गर्नुहोस् — यो निःशुल्क र तत्काल छ। विशिष्ट कानुनी मार्गदर्शनका लागि, हामी तपाईंलाई हाम्रो कानुनी साझेदारहरूको नेटवर्कसँग जोड्न सक्छौं।" },
        { q: "के यो सेवा निःशुल्क छ?", a: "हो। हरेक सुविधा — एआई कानुनी सहायक, दस्तावेज ढाँचा, ज्ञान हब, र समुदाय समर्थन — पूर्ण रूपमा निःशुल्क छ।" },
        { q: "यदि मलाई तात्कालिक सहयोग चाहियो भने?", a: "यदि तपाईं तुरुन्तै खतरा मा हुनुहुन्छ भने, महिला हेल्पलाइन 1145 वा प्रहरी 100 मा फोन गर्नुहोस्। हाम्रो आपतकालीन अनुभागमा सबै नम्बरहरू छन्।" },
      ],
    },
    aboutUs: {
      label: "हाम्रोबारे",
      title: "कानुनी सचेतनाबाट महिलाहरूलाई सशक्त बनाउँदै",
      desc: "Her Legal एक नेपालस्थित पहलकदमी हो जुन महिलाहरूलाई पहुँचयोग्य कानुनी जानकारी, आफ्नो कथाहरू साझा गर्न सुरक्षित समुदाय, र समय समयमा दयालु समर्थन प्रदान गर्न समर्पित छ।",
      cards: [
        { title: "हाम्रो उद्देश्य", desc: "शिक्षा, सामुदायिक समर्थन, र पहुँचयोग्य स्रोतहरूमार्फत नेपाली महिलाहरू र उनीहरूको कानुनी अधिकारहरूको बीचको दूरीलाई पुल गर्ने।" },
        { title: "हाम्रो दृष्टिकोण", desc: "एक नेपाल जहाँ हरेक महिला आफ्नो अधिकारहरूको बारेमा जानकार छ, बोल्न सक्षम छ, र न्यायतर्फको यात्रा मा समर्थित छ।" },
        { title: "हाम्रो मूल्यहरू", desc: "सुरक्षा, गोपनीयता, समानुभूति, र हरेक महिलाको गरिमा र कानुनी सुरक्षाप्रति अडिग विश्वास।" },
      ],
    },
    campaigns: {
      label: "कृयाशीलता",
      title: "अभियान र कार्यक्रमहरू",
      items: [
        { title: "आफ्नो अधिकार जान्नुहोस्", tag: "कार्यशाला", desc: "नेपालका सबै सात प्रदेशहरूमा निःशुल्क कानुनी साक्षरता कार्यशालाहरू, घरेलु हिंसा, सम्पत्ति अधिकार, र कार्यस्थल संरक्षणहरू समेटेर।" },
        { title: "सुरक्षित स्वर", tag: "अभियान", desc: "एक गुमनाम कथावाचन अभियान जसले महिलाहरूलाई आफ्ना अनुभवहरू साझा गर्न र समुदायमा एक अर्काबाट सहारा पाउन सशक्त बनाउँछ।" },
        { title: "साथी हेल्पलाइन", tag: "सेवा", desc: "कानुनी सल्लाहकार, परामर्शदाता, र आपतकालीन समर्थन सेवाहरू सँग महिलाहरूलाई गोपनीय रूपमा जोड्ने हेल्पलाइन।" },
      ],
    },
    contactHelp: {
      label: "सम्पर्कमा रहनुहोस्",
      title: "सम्पर्क र सहयोग",
      desc: "हामीलाई सम्पर्क गर्नुहोस्। चाहे तपाईंलाई कानुनी मार्गदर्शन चाहियो, आफ्नो कथा साझा गर्न चाहनुहुन्छ, वा केवल कसैसँग कुरा गर्न चाहानुहुन्छ — हामी यहाँ छौं।",
      emergencyTitle: "आपतकालीन हेल्पलाइनहरू",
      emailTitle: "हामीलाई इमेल गर्नुहोस्",
      generalInquiry: "सामान्य सोधपुछका लागि:",
      email: "hello@herlegal.org",
      followTitle: "हामीलाई फलो गर्नुहोस्",
      socials: ["Facebook", "Instagram", "Twitter"],
    },
    confessions: {
      label: "आफ्नो कथा साझा गर्नुहोस्",
      title: "तिम्रो आवाज, तिम्रो सत्य",
      desc: "आफ्ना अनुभवहरू अनाम रूपमा साझेदार गर्नुहोस्। तपाईं एक्लो हुनुहुन्न।",
      placeholder: "तिमी के साझा गर्न चाहन्छौ?",
      anonymous: "गुमनाम रूपमा पोस्ट गर्नुहोस्",
      posting: "पद प्रवेश गर्दै...",
      share: "शेयर →",
      anonymousAuthor: "अनाम",
      replyPlaceholder: "उत्तर लेख्नुहोस्...",
      reply: "उत्तर",
    },
    news: {
      label: "अपडेटहरू",
      title: "समाचार र पत्रिका",
      articles: [
        { title: "प्रदेश २ मा नयाँ कानुनी सहायता केन्द्रहरू खुल्दैछन्", date: "जुन २८, २०८३", excerpt: "प्रदेश २ भरमा महिला ग्रामीण क्षेत्रहरूका लागि निःशुल्क कानुनी परामर्श प्रदान गर्न पाँच नयाँ कानुनी सहायता केन्द्रहरू खुल्दैछन्।" },
        { title: "घरेलु हिंसा कानून संशोधन: तपाईंले जान्नु पर्ने कुरा", date: "जुन १५, २०८३", excerpt: "घरेलु हिंसा कानूनमा हालैका संशोधनहरूले पीडितहरूको सुरक्षालाई सुदृढ पार्दछन्। यहाँ सरल भाषा मा यसको संक्षिप्त विवरण छ।" },
        { title: "Her Legal ले ५०० महिलासम्म सहयोग पुर्‍याउने माइलस्टोन छुनुहोस्", date: "मे ३०, २०८३", excerpt: "हामी विनम्रतापूर्वक साझा गर्न चाहन्छौं कि Her Legal ले अब नेपालभरि ५०० भन्दा बढी महिलाहरूसँग कानुनी मार्गदर्शन र समर्थन प्रदान गरेको छ।" },
      ],
    },
    team: {
      label: "व्यक्ति",
      title: "हाम्रो टोली",
      members: [
        { name: "आराी गुरुङ", role: "", initials: "AG" },
        { name: "दलसारा सोती मगर", role: "", initials: "DSM" },
        { name: "नन्दानी सेवा", role: "", initials: "NS" },
        { name: "सोफिया कुँवर", role: "", initials: "SK" },
      ],
    },
    notFound: {
      title: "पृष्ठ भेटिएन",
      desc: "तपाईं खोजिरहनुभएको पृष्ठ अस्तित्वमा छैन वा सारिएको छ।",
      goHome: "गृहमा जानुहोस्",
    },
  },
};

const STORAGE_KEY = "herlegal_language";

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    if (typeof window === "undefined") return "en";
    const saved = window.localStorage.getItem(STORAGE_KEY);
    return saved === "ne" ? "ne" : "en";
  });

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, lang);
  }, [lang]);

  const value = useMemo(() => ({
    lang,
    setLanguage: setLang,
    t: (key) => {
      const parts = key.split(".");
      return parts.reduce((obj, part) => obj?.[part], translations[lang]) ?? key;
    },
    translations: translations[lang],
  }), [lang]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
